### ISSUE TITLE
(Web Demo) Game behaves weirdly on launch 

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/GFR_bugs#1]
Submitter: Jonah
Email: jjameson@aol.com
I came here from the announcement on Galaxytrail's twitter, but when I clicked the web demo, it took a solid 10 minutes before the screen finally wasn't black.

The logo pops up, so I click on the screen, and it goes black again for 2 minutes. After that, clicking the logo wasn't doing anything, so I refreshed the page. 10 more minutes of loading, and then my speakers were exploding with incredibly obnoxious music that just looped the words "PIZZA DELIVERY" while the sprites were flickering rapidly between the player character and something that looked like Spider-man and pizza logos were taking up the entire screen. This logo hung when I started the game; sound was playing, but I could not see anything through the pizza.

Either this is a very bizarre bug, or an elaborate and extremely unprofessional joke. I will have to buy a new set of speakers as a result, so to say that I am very disappointed with this game is an understatement. I will not be buying this game on release, especially if this is not fixed. Shame on GalaxyTrail for publishing a game with such an absurdly broken demo.

**Comment by FlutterSprite** [comment]
Working as intended.
