### ISSUE TITLE
1-2 eggplant statue house - enemy once got stuck in floor

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/GFR_bugs#19]
Submitter: Patrick Murphy
Email: italiangamer97@gmail.com
In the house of eggplant statues in Course 1-2, I noticed that an enemy managed to get stuck in the floor. Unsure of how I triggered it, but I was able to get the enemy out of the floor and defeat it. Perhaps I did something with one of the statues there?

**Comment by FlutterSprite** [comment]
Probably related to #5 - once I get some fixes in for that, things like this shouldn't happen as much, if at all!

**Comment by FlutterSprite** [comment]
Since #5 is fixed, this one seems to be fixed too!
