### ISSUE TITLE
[web demo] Thrown enemies going thru terrain

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/GFR_bugs#21]
Submitter: Zzzzzx
Email: jako3334074@gmail.com
Enemies thrown while right in front of a surface will occasionally go thru terrain.  Most easily testable with stage 2's first three enemies and the left side of the solid platform they start on.  May also have to do with another enemy being in the way, not sure.

vidya: https://youtu.be/-ZwfiBVapp8

**Comment by FlutterSprite** [comment]
Thanks for the video! This is related to #5 - I'll spend a lot of time looking into this soon.

**Comment by FlutterSprite** [comment]
Haven't been able to reproduce since, so considering this fixed!
