### ISSUE TITLE
No way to exit demo

### ISSUE THREAD

**Issue by samaralarkin** [GalaxyTrail/GFR_bugs#31]
The "return" button on the stage select screen is selectable, but does nothing.

**Comment by FlutterSprite** [comment]
Whoops!!!!!!!!!

**Comment by samaralarkin** [comment]
(related, and probably not worth its own issue: perhaps ESC as an alternate default ingame menu key?)

**Comment by FlutterSprite** [comment]
You can rebind the ingame menu key, but currently ESC cancels out your key input on the binding menu so it's not bindable unfortunately! If there's demand for it, I could change how this works in the future.

**Comment by FlutterSprite** [comment]
Main menu added in v1.4, which includes an exit game option!
