### ISSUE TITLE
[Steam Demo 1.3] - Spike ball enemies halt and reset death delay timer after going offscreen

### ISSUE THREAD

**Issue by SP3Ctator** [GalaxyTrail/GFR_bugs#34]
The big Spike ball enemies (on Stage 1-3) have a few seconds of delay before exploding after you've dealt enough damage to them. That death timer will be stopped if you move away far enough to offscreen them. Upon coming close again to such "defeated" enemy, their death timer will be reset and the explosion animation will be played out in full again. During that time they will sometimes jump around as if their AI wasn't realizing they are supposed to be dying.

**Comment by FlutterSprite** [comment]
Easy fix for this edge case - I'll make sure they don't despawn if they're out of health, so their death animation plays in its entirety.

**Comment by FlutterSprite** [comment]
Fixed in 1.4.
