### ISSUE TITLE
[Steam Demo 1.3] - JetLag bug

### ISSUE THREAD

**Issue by SP3Ctator** [GalaxyTrail/GFR_bugs#35]
This bug can be encountered on Stage 1-3, where you can interact with Jette.

If you happen to hop onto Jette while holding one of the horizontal movement directions and descending at the same time, then oftentimes Jette's horizontal movement speed will be capped much below her usual max speed.

Jette will regain the intended max speed if the horizontal movement button you were holding is released, or if Jette's horizontal movement is stopped (like from hitting a wall).

Demonstration here:
https://youtu.be/hnmKqCCu3Ys

**Comment by FlutterSprite** [comment]
Jette's acceleration and top speed caps are very, very old code - I'll have to take a look back at this and see how it works, I could probably do it much better now.

**Comment by FlutterSprite** [comment]
Fixed in 1.4!
