### ISSUE TITLE
[Steam Beta 1.4] - 1-2 Miniboss' rock issue

### ISSUE THREAD

**Issue by SP3Ctator** [GalaxyTrail/GFR_bugs#39]
In the course 1-2 the miniboss' rock throw attack is currently broken.

When the miniboss releases the rock, it will be set flying in a straight horizontal line close to the ceiling. The rock will phase through walls and Rena, should she stand in its way, but it can still be grappled and thrown back, dealing damage and progressing the fight.

Failing to grapple the rock will possibly softlock the game, as the boss' pattern probably prohibits it from throwing another rock if there is one already spawned and intact.

**Comment by FlutterSprite** [comment]
Augh!!

**Comment by Abel9210** [comment]
[Possibly?](https://puu.sh/A4FGT/a6840bd60e.mp4)

**Comment by FlutterSprite** [comment]
I have this fixed in my build of the game - the update will have to wait until Strife can be more available, unfortunately. In the meantime, you can press H on the course select screen to unlock all courses and skip it.

**Comment by FlutterSprite** [comment]
Thanks for bringing this up by the way! This exactly the sort of dumb thing I was afraid to miss going up, hehe

**Comment by FlutterSprite** [comment]
Fixed in my build for sure!
