### ISSUE TITLE
[Steam Beta 1.4] - 1-2 Commander Hurgh in his ship

### ISSUE THREAD

**Issue by SP3Ctator** [GalaxyTrail/GFR_bugs#40]
Hurgh remains in his Escape ship in the starting cutscene of 1-2 if you exit to the menu after it and restart (might even complete this level or visit some other levels in the meantime). That way the issue brakes Hurgh's movement in the scene. The "Restart Level" option fixes this.

https://imgur.com/a/QwPGJpb

**Comment by FlutterSprite** [comment]
Whoof, weird one! Fixed!
