### ISSUE TITLE
Occasionally grappling onto a moving object and then hitting a wall does not cut off the grapple

### ISSUE THREAD

**Issue by ThatEps** [GalaxyTrail/GFR_bugs#45]
Example in 1-4:
![bye](https://user-images.githubusercontent.com/38583427/39083065-6bd93054-4566-11e8-8c23-6d3a036a5a66.gif)

**Comment by FlutterSprite** [comment]
This is the intended behavior - the grappling hook is meant to be left behind on whatever surface cuts off the grapple to the moving object. The visual is a little funky, though, and I'll see what I can do to make it look more obvious what's going on.

**Comment by FlutterSprite** [comment]
I fixed the visuals on this to make it clearer that it's supposed to be happening - considering this fixed for now!
