### ISSUE TITLE
[Steam Beta 1.4] - "Pause" alternative binding in Gamepad Config is not modifiable. Can cause strange behaviour

### ISSUE THREAD

**Issue by AdamPMatecki** [GalaxyTrail/GFR_bugs#48]
Description: The gist of the issue is that the alternative binding for the "Pause" action in Gamepad Config rebinding section is not responding. This only happens in rebinding for gamepad. For keyboard it works fine.

Additionally, though it's random and not easily reproducible: trying to set this alternative binding for "Pause" might cause other bindings to be also unresponsive for several menu moves, mostly on the alternative side (scrolling to first column most time disables the bug)

**Comment by FlutterSprite** [comment]
Fixed! I just bungled up some copy-pasted code before.
