### ISSUE TITLE
[Steam Beta 1.4] Only one gamepad can control the game. Disconnecting the active gamepad will not enable the other viable one.

### ISSUE THREAD

**Issue by AdamPMatecki** [GalaxyTrail/GFR_bugs#49]
Description: Only the recently enabled gamepad will be usable in the situation where two of them are on at the same time. Disabling the currently working pad will not enable the another one that is turned on.

Reproduced on: X360 Gamepad + F710 (also Xinput)
1. Open the game with one pad on or both pads on. Turn on the 2nd gamepad if you didn't already.
- Only one gamepad will be responding.
2. Turn off the gamepad that is responding
- Second gamepad will still not respond.

**Comment by FlutterSprite** [comment]
Fixed! Pressing a button on a gamepad will now set it as the 'active' gamepad automatically, and any connected gamepad can be used to control the game (unless you have more than 8 connected gamepads for some reason - I had to cut it off somewhere)
