### ISSUE TITLE
Linux version launch error

### ISSUE THREAD

**Issue by goshaag** [GalaxyTrail/GFR_bugs#59]
Gives this after launching
![error](https://user-images.githubusercontent.com/45618401/49493722-bc6be700-f88f-11e8-9e2f-c4c0d604bc09.png)

Error line from terminal:
`[ERROR:nacl_browser.cc(305)] Failed to open NaCl IRT file "/home/nasty/.local/share/Steam/steamapps/common/Grapple Force Rena/nacl_irt_x86_64.nexe": -4`

Im using Antergos 18.16

Demo version worked perfectly though.

**Comment by FlutterSprite** [comment]
That's a real headscratcher... I've only tested the Linux version on Ubuntu and that's the only version of Linux officially supported so far, but I'll see what there is to be done about this one if I can!

**Comment by FlutterSprite** [comment]
It looks like updating to a nw.js version may fix it - once the Steam plugin I'm using updates to support the latest nw.js build, I'll update it again and we'll see if that works!

**Comment by goshaag** [comment]
Reporting that as of version 1.0.7 it now totally works! Thanks for addressing it! :D

**Comment by FlutterSprite** [comment]
Cool!! I have no idea what I did!! I'm glad it works for you!!
