### ISSUE TITLE
Cesar Appears to Stops Summoning Enemies (Not a Bug, Slightly Confusing Design)

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/GFR_bugs#61]
Submitter: Dazl
(I realized this wasn't the softlock I initially thought it was during my playthrough and have re-written this accordingly.)

Cesar will intentionally stall and wait for the player to throw an enemy so that he can counter-portal it to hurt the player, that much is clear. However, scoring very early damage or getting a bad throw into a quickly-disappearing portal can make it appear that there are no more enemies in the room, giving the impression that the boss has softlocked.

Videos:
Waiting on the hollow summon, not realizing it's an enemy action and not time-based https://www.twitch.tv/videos/344881913?t=01h16m31s
Confirming that his stall for counter-attack is normal, expected behavior https://www.twitch.tv/videos/344881913?t=01h16m44s
Hitting Cesar with an enemy, not realizing that the current hollow must be destroyed before a new one will be summoned in. Did not see it on the far side of the screen after checking the other side of the room: https://www.twitch.tv/videos/344881913?t=01h19m19s

**Comment by FlutterSprite** [comment]
Adding a little indicator showing where offscreen enemies are (like in the Pine boss fight) might be a good solution to this problem - thanks for your feedback!

**Comment by FlutterSprite** [comment]
Added an indicator for offscreen enemies in 3-5!
