### ISSUE TITLE
Frustrating auto-aim in 2-5 boss

### ISSUE THREAD

**Issue by rarsneezes** [GalaxyTrail/GFR_bugs#62]
The auto-aim during this boss prioritizes grabbing the ceiling over grabbing crystals. It wasn't unplayable, but perhaps more frustrating than it needed to be.

**Comment by FlutterSprite** [comment]
It shouldn't be too hard to make sure the auto-aim prioritizes the crystals in this fight. Thanks for letting me know!

**Comment by FlutterSprite** [comment]
Fixed! The crystals will get pulled down more reliably now.
