### ISSUE TITLE
major slow down 

### ISSUE THREAD

**Issue by rodnigalloway** [GalaxyTrail/GFR_bugs#88]
i am experiencing major slow down issues that i didnt encounter in the demo. please help!

**Comment by rodnigalloway** [comment]
experiencing major slow down issues!

**Comment by FlutterSprite** [comment]
I'm really sorry to hear that! Could you give some more information on the kind of system you're running? And are you experiencing slow down in certain parts of the game, or all the time?

**Comment by rodnigalloway** [comment]
Everything is working pretty good right now 😎it’s a great game 🤩

Sent from my iPhone

On Mar 4, 2019, at 8:37 PM, FlutterSprite <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm really sorry to hear that! Could you give some more information on the kind of system you're running? And are you experiencing slow down in certain parts of the game, or all the time?

**Comment by FlutterSprite** [comment]
Ohh, glad to hear it! I hope you enjoy the whole game - let me know if you run into any other issues!
